spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:53306/db_kafka?useUnicode=true&characterEncoding=utf8
    username: root
    password: onion

  data:
    mongodb:
      uri: mongodb://onion:onion@127.0.0.1:27017/db_kafka
      database: db_kafka
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        format_sql: true

